source 'https://rubygems.org'

gem 'ridley', '~> 5.1.0'
gem 'sinatra', '~> 1.4.8'
gem 'json'
gem 'rake'
gem 'version_sorter'
gem 'i18n'
gem 'net-http-persistent', '~> 2.0'
gem 'redis'
gem 'fakeredis'
gem 'mixlib-archive'
gem 'retryable'
gem 'rufus-scheduler'
gem 'yard', '~> 0.9.9'
gem 'yard-chefdoc', '~> 0.1.0'
gem 'puma'
